.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager (Dark Knightz build)
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X. It manages windows in tiled, monocle
and floating layouts. This version is a custom build by fam007e, featuring
various patches and integrated scripts for system management.
.P
In tiled layouts windows are managed in a master and stacking area. The master
area on the left contains one window by default, and the stacking area on the
right contains all other windows. The number of master area windows can be
adjusted.
.P
This build includes support for color temperature adjustment (warm mode),
custom factor (cfact) for resizing windows in the stack, and a set of
integrated management scripts found in the scripts directory.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr, then exits.
.SH USAGE
.SS Status bar
.TP
.B Button1
click on a tag label to display all windows with that tag.
.TP
.B Button3
click on a tag label adds/removes all windows with that tag to/from the view.
.SS Keyboard commands
.TP
.B Mod4\-Return
Zooms/cycles focused window to/from master area.
.TP
.B Mod4\-Shift\-Return
Start
.BR alacritty.
.TP
.B Mod4\-r
Spawn
.BR rofi
for launching other programs.
.TP
.B Control\-e
Spawn rofi emoji launcher.
.TP
.B Mod4\-c
Spawn rofi calculator.
.TP
.B Mod4\-s
Spawn rofi search (DuckDuckGo).
.TP
.B Mod4\-p
Spawn power menu.
.TP
.B Mod4\-slash
Show keybindings help.
.TP
.B Mod4\-w
Spawn wifi menu.
.TP
.B Mod4\-u
Spawn bluetooth menu.
.TP
.B Mod4\-b
Launch Brave Browser.
.TP
.B Mod4\-Shift\-b
Launch Tor Browser.
.TP
.B Mod4\-e
Launch Thunar file manager.
.TP
.B Mod4\-z
Launch Zed editor.
.TP
.B Mod4\-a
Launch Antigravity.
.TP
.B Mod4\-v
Launch VLC.
.TP
.B Mod4\-l
Lock screen (slock).
.TP
.B Mod4\-q
Close focused window.
.TP
.B Mod4\-Shift\-e
Quit dwm.
.TP
.B Mod4\-Shift\-n
Toggle warm color temperature.
.TP
.B Mod4\-j, Mod4\-k
Focus next/previous window.
.TP
.B Mod4\-Shift\-j, Mod4\-Shift\-k
Move focused window down/up the stack.
.TP
.B Mod4\-h, Mod4\-l
Decrease/increase master area size.
.TP
.B Mod4\-Shift\-h, Mod4\-Shift\-l
Decrease/increase window size in stack (cfact).
.TP
.B Mod4\-0
View all tags.
.TP
.B Mod4\-Shift\-0
Apply all tags to focused window.
.TP
.B Mod4\-[1..9]
View nth tag.
.TP
.B Mod4\-Shift\-[1..9]
Apply nth tag to focused window.
.SS Media Keys
.TP
.B AudioRaise/LowerVolume
Adjust master volume.
.TP
.B AudioMute
Toggle master mute.
.TP
.B MonBrightnessUp/Down
Adjust monitor brightness.
.TP
.B AudioPlay/Next/Prev/Stop
Media playback control.
.SH FILES
Autostart scripts are searched for in:
.IP "1. $XDG_DATA_HOME/dwm"
.IP "2. $HOME/.local/share/dwm"
.IP "3. $HOME/.dwm"
.P
Additional management scripts are located in the
.B scripts/
directory.
.SH SEE ALSO
.BR rofi (1),
.BR alacritty (1)
