#!/bin/sh
# dwm autostart — single unified autostart script
# Phase 1: Blocking setup (must complete before windows appear)
# Phase 2: Background services (compositor, notifications, polybar, tray apps)

# ── Phase 1: Blocking ──────────────────────────────────────────────────────────
# Disable DPMS and screen blanking (prevents GPU/display wake issues)
xset s off
xset s noblank
xset -dpms

# Set XDG environment variables for portals and desktop services
export XDG_CURRENT_DESKTOP=dwm
export XDG_SESSION_TYPE=x11

# Export display env to systemd/dbus in parallel (both are IPC round-trips)
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user import-environment DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE &
fi
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE 2>/dev/null &
wait

# Restart xdg-desktop-portal so it inherits the correct environment variables (crucial for flameshot/portals)
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user restart xdg-desktop-portal xdg-desktop-portal-gtk 2>/dev/null &
fi

# ── Phase 2: Background services ───────────────────────────────────────────────

# Source theme environment so tray apps (e.g. flameshot) inherit QT_QPA_PLATFORMTHEME
# This file is generated by theme-apply.sh and updated on every theme change.
THEME_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/dwm/theme-env.sh"
[ -f "$THEME_ENV" ] && . "$THEME_ENV"

# Get the directory where this script lives to find sibling scripts
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Export DWM runtime paths so polybar modules and scripts can resolve correctly.
# SCRIPT_DIR is ~/.local/share/dwm/scripts, so dirname gives the data root.
export DWM_DATA_DIR="$(dirname "$SCRIPT_DIR")"
export DWM_POLYBAR_SCRIPTS="$HOME/.config/polybar/scripts"

# Wallpaper rotation (every 30 mins)
"$SCRIPT_DIR/wallpapersSS" &

# Compositor
picom -b 2>/dev/null &

# Notification daemon
dunst 2>/dev/null &

# Polkit authentication agent (try common agents)
for agent in \
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 \
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 \
    /usr/libexec/polkit-gnome-authentication-agent-1 \
    /usr/lib/polkit-kde-authentication-agent-1 \
    /usr/libexec/polkit-kde-authentication-agent-1 \
    /usr/bin/lxpolkit \
    /usr/lib/lxpolkit/lxpolkit; do
    if [ -x "$agent" ]; then
        "$agent" &
        break
    fi
done

# Launch Polybar (no stderr suppression — surface errors during debugging)
"$HOME/.config/polybar/launch.sh" &

# Tray Applets
flameshot &
nm-applet &
command -v blueman-applet >/dev/null 2>&1 && blueman-applet &

# Periodic Football Match Updates (every 1 hour)
(while true; do "$SCRIPT_DIR/football_matches" >/dev/null 2>&1; sleep 3600; done) &

# Launch terminal with tmux on startup
TERM_CMD="xterm"
for t in ghostty alacritty kitty st; do
    if command -v "$t" >/dev/null 2>&1; then
        TERM_CMD="$t"
        break
    fi
done
$TERM_CMD -e tmux &

dex -a 2>/dev/null
