#!/usr/bin/env sh

# Fetch weather data from OpenWeather API-Add your API key & latitude and longitude
API_KEY=""
LAT=""
LON=""
URL="https://api.openweathermap.org/data/2.5/weather?lat=${LAT}&lon=${LON}&appid=${API_KEY}"

WEATHER_DATA=$(curl -s $URL)

# Extract weather information using jq
TEMP=$(echo $WEATHER_DATA | jq '.main.temp' -r)
FEELS_LIKE=$(echo $WEATHER_DATA | jq '.main.feels_like' -r)
WEATHER_MAIN=$(echo $WEATHER_DATA | jq '.weather[0].main' -r)
WEATHER_DESCRIPTION=$(echo $WEATHER_DATA | jq '.weather[0].description' -r)
HUMIDITY=$(echo $WEATHER_DATA | jq '.main.humidity' -r)
WIND_SPEED=$(echo $WEATHER_DATA | jq '.wind.speed' -r)

# Convert temperature from Kelvin to Celsius using awk
TEMP_C=$(awk "BEGIN {print $TEMP - 273.15}")
FEELS_LIKE_C=$(awk "BEGIN {print $FEELS_LIKE - 273.15}")

# Define icons for weather conditions
case $WEATHER_MAIN in
  Clear)
    ICON="☀️"
    ;;
  Clouds)
    ICON="☁️"
    ;;
  Rain)
    ICON="🌧️"
    ;;
  Drizzle)
    ICON="🌦️"
    ;;
  Thunderstorm)
    ICON="⛈️"
    ;;
  Snow)
    ICON="❄️"
    ;;
  Mist|Smoke|Haze|Dust|Fog|Sand|Ash|Squall|Tornado)
    ICON="🌫️"
    ;;
  *)
    ICON="🌈"
    ;;
esac

# Print weather information with icons
echo "Weather Information for Darlawn:"
echo "Temperature: ${TEMP_C}°C (Feels like ${FEELS_LIKE_C}°C)"
echo "Condition: ${WEATHER_MAIN} (${WEATHER_DESCRIPTION}) ${ICON}"
echo "Humidity: ${HUMIDITY}%"
echo "Wind Speed: ${WIND_SPEED} m/s"

exit 0
