#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/Wallpapers"

# Ensure the directory exists
mkdir -p "$WALLPAPER_DIR"

while true; do
    feh --randomize --bg-fill "$WALLPAPER_DIR"
    sleep 1800  # Sleep for 30 minutes (1800 seconds)
done
